In [4]:
import numpy as np
list1=[12,3,432,55,123,4]
array = np.array(list1)
print(array[0])
print(array)
print(array[0:4:2])

12
[ 12   3 432  55 123   4]
[ 12 432]


In [5]:
a = np.array ([[2,3,4],[5,6,7],[10,20,30]])
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [10 20 30]]


In [6]:
a[0:1,1:2]

array([[3]])

In [7]:
a[2:,2:]

array([[30]])

In [8]:
a[1:2,1:]

array([[6, 7]])

In [10]:
a[0:1,1:]

array([[3, 4]])

In [11]:
a[0:2]

array([[2, 3, 4],
       [5, 6, 7]])

In [12]:
a[1:2:,1:2]

array([[6]])

In [15]:
a[1:3,1:3]

array([[ 6,  7],
       [20, 30]])

In [16]:
a = np.array ([[[2,3,4],[5,6,7],[10,20,30]],[[12,13,14],[25,26,27],[310,320,330]]])
print(a)
print(a.ndim)

[[[  2   3   4]
  [  5   6   7]
  [ 10  20  30]]

 [[ 12  13  14]
  [ 25  26  27]
  [310 320 330]]]
3


In [17]:
a[1::,0::,2::]

array([[[ 14],
        [ 27],
        [330]]])

In [18]:
a[0:1,1:2,1:]

array([[[6, 7]]])

In [19]:
a[0:1,1:,1:2]

array([[[ 6],
        [20]]])

In [20]:
a[0:,0:,0:]

array([[[  2,   3,   4],
        [  5,   6,   7],
        [ 10,  20,  30]],

       [[ 12,  13,  14],
        [ 25,  26,  27],
        [310, 320, 330]]])

In [24]:
a[::]

array([[[  2,   3,   4],
        [  5,   6,   7],
        [ 10,  20,  30]],

       [[ 12,  13,  14],
        [ 25,  26,  27],
        [310, 320, 330]]])

In [25]:
a[1:1:1]

array([], shape=(0, 3, 3), dtype=int32)

In [28]:
a[1:,0:2,2:]

array([[[14],
        [27]]])

In [ ]:
a[0][1][1]

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.random.rand(2,5)

array([[0.63471684, 0.78386989, 0.96464419, 0.36509487, 0.44684231],
       [0.8043417 , 0.45190906, 0.96518301, 0.12713519, 0.15021349]])

In [34]:
np.random.randint(1,12,3)

array([7, 5, 3])

In [35]:
np.linspace(2,20,10,retstep=True)

(array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.]), 2.0)

In [54]:
arr = np.linspace(1,50, num= 50,retstep=True) 
# last included
arr

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
        40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.]),
 1.0)

In [39]:
np.arange(2,20,4)

array([ 2,  6, 10, 14, 18])

In [53]:
arr = np.arange(0,20,2) ## last element is not icluded 
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [40]:
arr = np.random.randn(1,5,3)
arr

array([[[-0.286776  , -0.02295521, -0.50612847],
        [-0.50095541,  1.07986136, -1.19137928],
        [ 0.89697731, -1.50031083, -0.7219397 ],
        [-0.59548712,  0.54700995,  0.97695968],
        [ 0.49140025,  1.0394022 , -0.32878457]]])

In [41]:
arr = np.random.randint(10,20, size = 10)
print(f"{arr=}")
sort_array = np.sort(arr)
sort_array

arr=array([16, 11, 17, 15, 11, 12, 16, 18, 15, 14])


array([11, 11, 12, 14, 15, 15, 16, 16, 17, 18])

In [42]:
arr = np.array([[4,5],[6,7]])
arr1 = np.array([[14,15],[16,17]])
arr2 = np.array([[14,15],[23,43]])
new_arr = np.concatenate([arr1,arr,arr2],axis=1)

print(f"\n{new_arr=}")


new_arr=array([[14, 15,  4,  5, 14, 15],
       [16, 17,  6,  7, 23, 43]])


In [43]:
np.ceil(2.2)

3.0

In [44]:
np.floor(2.2)

2.0

In [45]:
np.around(2.2)

2.0

In [46]:
list1 = [3,4,5,6,7,8,9]

index_list = list1.index(5)
index_list

2

In [50]:
a=np.array([12,4,5,4235,6,3,5])
s=np.where(a>5)
# s[0].tolist()
s

(array([0, 3, 4], dtype=int64),)

In [51]:
arr1 = np.array([[2, 3, 4], [5, 6, 7]])
print(arr1)
print('*'*50)
arr2 = np.array([[21, 31, 41], [51, 61, 71]])
print(arr2)
print('*'*50)
nw=np.add(arr1,arr2)
print(nw)
print('*'*50)
print(arr1+arr2)
arr1 = np.array([[2, 3, 4], [5, 6, 7]])
print(arr1)
print('*'*50)
arr2 = np.array([[21, 31, 41], [51, 61, 71]])
print(arr2)
print('*'*50)
nw=np.multiply(arr1,arr2)
print(nw)
print('*'*50)
print(arr1*arr2)
print('*'*50)
s=np.dot(arr1,arr2)
print(s)


[[2 3 4]
 [5 6 7]]
**************************************************
[[21 31 41]
 [51 61 71]]
**************************************************
[[23 34 45]
 [56 67 78]]
**************************************************
[[23 34 45]
 [56 67 78]]
[[2 3 4]
 [5 6 7]]
**************************************************
[[21 31 41]
 [51 61 71]]
**************************************************
[[ 42  93 164]
 [255 366 497]]
**************************************************
[[ 42  93 164]
 [255 366 497]]
**************************************************


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [52]:
arr1 = np.array([[2, 3],[ 4,5]])
print(f"Array1 = \n{arr1}")
arr2 = np.array([[1,4 ],[ 3,6]])
print(f"Array2 = \n{arr2}")

# arr = arr1 * arr2
# print('*'*30)
arr = np.dot(arr1,arr2)
print(arr)

Array1 = 
[[2 3]
 [4 5]]
Array2 = 
[[1 4]
 [3 6]]
[[11 26]
 [19 46]]


In [55]:
arr = np.array([4,5,6,7,8])
arr1 = np.array([14,15,16,17,18])

new_arr = np.append(arr,arr1)

print(f"{new_arr=}")

new_arr=array([ 4,  5,  6,  7,  8, 14, 15, 16, 17, 18])


In [56]:
arr1 = np.array([[4,5,6],[7,8,9]])
print(f"Array1 = \n {arr1} ")
arr2 = np.array([[14,15,16],[17,18,19]])
print(f"Array2 = \n {arr2} ")

new_arr = np.append(arr1,arr2, axis= 0) ## axis = 0 >> adding rows
 
print(f"New Array = \n {new_arr}")

Array1 = 
 [[4 5 6]
 [7 8 9]] 
Array2 = 
 [[14 15 16]
 [17 18 19]] 
New Array = 
 [[ 4  5  6]
 [ 7  8  9]
 [14 15 16]
 [17 18 19]]


In [57]:
arr1 = np.array([[4,5,6],[7,8,9]])
print(f"Array1 = \n {arr1} ")
arr2 = np.array([[14,15,16],[17,18,19]])
print(f"Array2 = \n {arr2} ")

new_arr = np.append(arr1,arr2, axis= 1) ## axis = 1 >> adding columns
 
print(f"New Array = \n {new_arr}")

Array1 = 
 [[4 5 6]
 [7 8 9]] 
Array2 = 
 [[14 15 16]
 [17 18 19]] 
New Array = 
 [[ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [58]:
arr1 = np.array([[4,5,6],[7,8,9]])
print(f"Array1 = \n {arr1} ")
arr2 = np.array([[14,15,16],[17,18,19]])
print(f"Array2 = \n {arr2} ")
arr3 = np.array([[10,20,30],[50,60,70]])
print(f"Array3 = \n {arr3} ")
new_arr = np.concatenate([arr1,arr2,arr3], axis= 0) ## axis = 0 >> adding rows
 
print(f"New Array = \n {new_arr}")

Array1 = 
 [[4 5 6]
 [7 8 9]] 
Array2 = 
 [[14 15 16]
 [17 18 19]] 
Array3 = 
 [[10 20 30]
 [50 60 70]] 
New Array = 
 [[ 4  5  6]
 [ 7  8  9]
 [14 15 16]
 [17 18 19]
 [10 20 30]
 [50 60 70]]


In [59]:
import numpy as np
arr = np.array([[2, 3, 4], [5, 6, 7],[ 9, 10, 12],[ 13,14,15]])
print(arr)
result = np.where(arr%2==0)
print(result)
row_index = result[0].tolist()
columns_index = result[1].tolist()

print(row_index)
print(columns_index)

[[ 2  3  4]
 [ 5  6  7]
 [ 9 10 12]
 [13 14 15]]
(array([0, 0, 1, 2, 2, 3], dtype=int64), array([0, 2, 1, 1, 2, 1], dtype=int64))
[0, 0, 1, 2, 2, 3]
[0, 2, 1, 1, 2, 1]


In [60]:
# ACCESS ELEMENTS IN ARRAY
import numpy as np
array = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

for i in array:
    for j in i:
        print(j)
print(array.ndim) 

1
2
3
4
5
6
7
8
9
10
11
12
2


In [62]:
# nditer()
array = np.array([[[2,3],[4,5]],[[6,7],[8,9]]])

array_iter = np.nditer(array)
print(array_iter)

print(next(array_iter))
print(next(array_iter))
print(next(array_iter))
print(next(array_iter))

2
3
4
5


In [63]:
# ndenumerate()
arr = np.array([2,3,4,5,6])

for index,value in np.ndenumerate(arr):
    print(index,value)

(0,) 2
(1,) 3
(2,) 4
(3,) 5
(4,) 6


In [64]:
arr = np.identity(5,dtype=int)
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [65]:
np.random.seed(9)
arr = np.random.randint(10,100, size = 7)
arr

array([64, 66, 32, 75, 32, 62, 69])

In [66]:
from scipy import stats

In [67]:
np.random.seed(12)
array2 = np.random.randint(10,15, size =(3,3))
print(array2)

[[13 13 11]
 [12 13 13]
 [14 10 11]]


In [68]:
mode = stats.mode(array2)
mode

ModeResult(mode=array([[12, 13, 11]]), count=array([[1, 2, 2]]))

In [69]:
median = np.median(array2)
median

13.0

1. np.mean(a)
2. np.median(a)
3. mode()
4. np.var(a)
5. standard deviation()
np.std(a)
6. np.min(a)
7. np.max(a)

In [70]:
np.sin(30)
# wrong

-0.9880316240928618

In [71]:
sin_30 = np.sin(np.pi/6)  # >> 0.5
sin_30
# correct

0.49999999999999994

In [77]:
arr = np.array([58,30,45,60,90])

arr_deg = np.deg2rad(arr)
print(arr_deg)

arr_sin = np.sin(arr_deg)
print(arr_sin)

arr_deg = np.rad2deg(arr)
print(arr_deg)
rad_arr = np.array([1.01229097, 0.52359878, 0.78539816, 1.04719755, 1.57079633])
deg = np.rad2deg(rad_arr)
print(deg)

[1.01229097 0.52359878 0.78539816 1.04719755 1.57079633]
[0.8480481  0.5        0.70710678 0.8660254  1.        ]
[3323.15521176 1718.87338539 2578.31007809 3437.74677078 5156.62015618]
[58.00000022 30.00000025 44.99999981 59.99999993 90.00000018]


In [80]:
data = [10,20,12,14,15,17,150,11,18,13,12]
print(np.log(data))
print(f"Mean = {np.mean(data)}")


[2.30258509 2.99573227 2.48490665 2.63905733 2.7080502  2.83321334
 5.01063529 2.39789527 2.89037176 2.56494936 2.48490665]
Mean = 26.545454545454547


In [ ]:
3x + 5y = 20
4x + 7y = 30
---------------

x = ? -10
y = ? 10


In [81]:
import numpy as np
arrA = np.array([[3,5],[4,7]])
arrB = np.array([20,30])
print(f"Array A = \n{arrA}")
print(f"Array B = \n{arrB}")

result = np.linalg.solve(arrA,arrB)
result

Array A = 
[[3 5]
 [4 7]]
Array B = 
[20 30]


array([-10.,  10.])

In [82]:
arr = np.array([[3,2],[4,6]])
print(arr)
tr_arr = np.transpose(arr)
print(tr_arr)

[[3 2]
 [4 6]]
[[3 4]
 [2 6]]


In [83]:
arr = np.array([[3,2],[4,6]])
print(arr)
det = np.linalg.det(arr)
print(det)

[[3 2]
 [4 6]]
10.000000000000002


In [84]:
arr = np.array([[3,2],[4,6]])
print(arr)
inv = np.linalg.inv(arr)
print(inv)

[[3 2]
 [4 6]]
[[ 0.6 -0.2]
 [-0.4  0.3]]


In [85]:
arr1 = np.array([10,20,30,40,50])
arr2 = arr1.copy()  # Deep Copy
print(f"Array1 = {arr1}")

print(f"Array2 = {arr2}")

arr2[2] = 100

print(f"Array1 = {arr1}")

print(f"Array2 = {arr2}")

Array1 = [10 20 30 40 50]
Array2 = [10 20 30 40 50]
Array1 = [10 20 30 40 50]
Array2 = [ 10  20 100  40  50]


In [86]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr = arr1 * arr2
print(arr)

[ 10  40  90 160 250]


In [87]:
arr1 = np.array([2])
arr2 = np.array([10,20,30,40,50])

arr = arr1 * arr2
print(arr)

[ 20  40  60  80 100]


In [88]:
arr1 = np.array([2,3])
arr2 = np.array([10,20,30,40,50])

arr = arr1 * arr2
print(arr)

ValueError: operands could not be broadcast together with shapes (2,) (5,) 

In [90]:
arr1 = np.array([[2,3],[4,5],[6,7],[8,9]])
arr2 = np.array([10,20])

arr = arr2 * arr1
print(arr)
# 2x2

[[ 20  60]
 [ 40 100]
 [ 60 140]
 [ 80 180]]


In [2]:
import numpy as np
s=np.array([12,3,4,52,4,53,13])
s1=s.size
s1

7

In [3]:
s=np.zeros(10)
s[5]=1
s

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [4]:
#  Reverse a vector (The first element becomes last)
s=np.arange(15,45)
s[0]=44
s[-1]=0
s

array([44, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,  0])

In [5]:


# use of all and any function in numpy?
s=np.array([56,30.5,60,45])
s1=np.any(s)
print(s1)
s=np.array([0,56,30.5,60,45])
s1=np.all(s)
s1



True


False

In [6]:
#  3x3 matrix  values ranging from 0 to 8
s=np.arange(0,9).reshape(3,3)
s

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
# 13. How to reverse the columns of a 2D array?
s=np.array([[12,3,4],[43,23,2]])
s1=np.transpose(s)
print(s1)
print('*'*30)


s2=np.flip(s,axis=1)
print(s2)
print('*'*30)




# reverse the rows of a 2D array?
s3=np.array([[12,3,4],[43,23,2]])
s3=np.flip(s3,axis=0)
print(s3)
print('*'*30)




[[12 43]
 [ 3 23]
 [ 4  2]]
******************************
[[ 4  3 12]
 [ 2 23 43]]
******************************
[[43 23  2]
 [12  3  4]]
******************************


In [10]:
s=np.array([1,2,0,0,4,0])
s1=np.where(s!=0)
s1

(array([0, 1, 4], dtype=int64),)

In [11]:
#  extract all numbers between a given range from a NumPy array?
s=np.array([12,34,3,6,5,7,3])
s1=np.where(s>2) and(s<8)
s1

array([False, False,  True,  True,  True,  True,  True])

In [13]:
# 2d array with 1 on the border and 0 inside
s=np.ones((5,5))
s[1:-1,1:-1]=0
s

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
#  5x5 matrix with values 1,2,3,4 just below the diagonal
s=np.ones((5,5))
print(s)
print('*'*25)
s[2:3,0:2]=2
s[3:4,0:3]=3
s[4:5,0:4]=4
print(s)



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
*************************
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 1. 1. 1.]
 [3. 3. 3. 1. 1.]
 [4. 4. 4. 4. 1.]]


In [35]:


# 8x8 matrix and fill it with a checkerboard pattern
s=np.zeros((8,8))
s[1::2,::2]=1
s[::2,1::2]=1
s



array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [19]:
# 5x3 matrix by a 3x2 matrix (real matrix product)
s=np.arange(1,16).reshape(5,3)
print(s)
print()
s1=np.arange(1,7).reshape(3,2)
print(s1)
print()
s2=np.dot(s,s1)
print(s2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

[[1 2]
 [3 4]
 [5 6]]

[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


In [20]:
# a 1Darray, negate all elements which are between 3 and 8, in place
s=np.random.randint(1,20,10)
print(s)
s1=np.where(s<3)
print('elements less than 3',s1)
s2=np.where(s>8)
print('elements greater than 8',s2)

[ 1 17  3 11 11  2 18 10  1  6]
elements less than 3 (array([0, 5, 8], dtype=int64),)
elements greater than 8 (array([1, 3, 4, 6, 7], dtype=int64),)


In [22]:
#  round away from zero a float array?
s=np.random.rand(5)
print(s)
s1=np.around(s)
print(s1)

[0.84393573 0.78653768 0.9996514  0.67830114 0.79110069]
[1. 1. 1. 1. 1.]


In [23]:


# find common values between the two arrays?
s=np.random.randint(1,20,10)
print(s)
s1=np.random.randint(1,20,10)
print(s1)
s3=np.intersect1d(s,s1)
print('interseted elements are:>',s3)



[13 17  8  4 13 17 19 16 13 19]
[ 5 19 18  4 13  4  2 10 12  1]
interseted elements are:> [ 4 13 19]


In [24]:
#  Create a vector of size 10 with values ranging from 0 to 1, both excluded
s=np.random.rand(10)
s

array([0.86606833, 0.0267392 , 0.6345286 , 0.28667394, 0.99773472,
       0.0903458 , 0.05409675, 0.50818719, 0.65964266, 0.91133031])

In [25]:
s=np.random.randint(0,4,size=(5,5))
print(s)
print("#"*30)
s[0::]=0,1,2,3,4
print(s)

[[3 0 2 0 2]
 [2 1 3 0 1]
 [0 0 3 0 2]
 [3 3 3 2 0]
 [2 1 0 3 2]]
##############################
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [26]:


s=np.zeros((5,5))
s=s+np.arange(5)
print(s)



[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [27]:
# sort an array by the nth column?
s=np.array([11,2,33,56,5,76])
s1=np.sort(s)[::-1]
s1

array([76, 56, 33, 11,  5,  2])

In [28]:
# swap two rows of an array?
s=np.random.randint(2,20,size=(4,3))
print(s)
s1=np.flip(s,axis=0)
print(s1)

[[ 4  2  2]
 [ 7 19  9]
 [11 11 15]
 [17  9 16]]
[[17  9 16]
 [11 11 15]
 [ 7 19  9]
 [ 4  2  2]]


In [30]:
# print only 3 decimal places in a python NumPy array? 
s=np.random.rand(5)
print(s)
s1=np.around(s,3)
print(s1)

[0.61202593 0.9238179  0.61055652 0.21324293 0.56782421]
[0.612 0.924 0.611 0.213 0.568]


In [31]:
# to convert 4D array to 2D array?
s=np.random.randint(1,20,size=(2,2,2,2))
print(s)
s1=s.reshape(4,4)
print(s1)

[[[[ 5  6]
   [ 2 17]]

  [[ 1 17]
   [ 9 13]]]


 [[[ 4  9]
   [ 8  5]]

  [[10 16]
   [10  9]]]]
[[ 5  6  2 17]
 [ 1 17  9 13]
 [ 4  9  8  5]
 [10 16 10  9]]


In [32]:
# number of rows and columns of a given matrix using NumPy
s=np.random.randint(1,20, size=(3,4))
print(s)
s1=s.shape
print('shape is : ',s1)

[[11 10  7  4]
 [19 13 13 10]
 [ 6  9 10 11]]
shape is :  (3, 4)
